dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - elasticsearch

# before install:
#   - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb && \
#     sudo dpkg -i --force-confnew elasticsearch-5.5.0.deb && \
#     sudo service elasticsearch start
install:
  - nvm install 8.9.3
before_script:
  - 'echo "cluster.name: croaker-cluster" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch restart
  - sleep 10
  - curl http://localhost:9200/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gradle check

# Turn off email notifications
notifications:
  email: false
