dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - elasticsearch

install:
  - nvm install 8.9.3
before_script:
  - 'echo "cluster.name: croaker-cluster" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch restart
  - sleep 10
  - curl http://localhost:9200/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Turn off email notifications
notifications:
  email: false
