dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  chrome: stable

env:
  - NODE_VERSION=8.9.3 ES_VERSION=5.5.0 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
install:
  - nvm install ${NODE_VERSION}
  - echo "skip 'gradle assemble' step"
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
before script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
script:
  - gradle build --continue


# Turn off email notifications
notifications:
  email: false
